[package]
name = "frozenight"
version = "0.1.0"
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = { version = "1.7.3", features = ["derive"] }
cozy-chess = "0.2.1"
nohash = "0.2.0"
rand = "0.8.5"
rand_pcg = "0.3.1"
