[package]
name = "frozenight"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = { version = "1.7.3", features = ["derive"] }
cozy-chess = "0.3"
nohash = "0.2.0"
parking_lot = "0.12.1"
